// Imports the old restaurant list (sheet "Viso") into D1.
//
//   node scripts/import-excel.ts "data/Vilnius restaurants.xlsx"     → dry-run report + data/import.sql
//   npx wrangler d1 execute food-review --remote --file data/import.sql
//
// The SQL is idempotent: places whose name already exists are skipped, so it can be re-run safely.
import ExcelJS from "exceljs";
import { writeFileSync } from "node:fs";
import { composeSearchText } from "../src/db/search.ts";
import { cleanCategory } from "./category-map.ts";
import { sqlLiteral } from "./sql.ts";

export interface ImportedPlace {
  row: number;
  name: string;
  rating: number | null;
  categories: string[];
  rawCategory: string | null;
  notes: string | null;
  website: string | null;
}

const CITY = "Vilnius";

function cellText(value: ExcelJS.CellValue): string | null {
  if (value === null || value === undefined) return null;
  if (typeof value === "object" && "text" in value) return String(value.text).trim() || null;
  if (typeof value === "object" && "richText" in value) return value.richText.map((r) => r.text).join("").trim() || null;
  return String(value).trim() || null;
}

/** 5-point rating → 10-point (×2). */
export function convertRating(value: ExcelJS.CellValue, row: number): number | null {
  if (value === null || value === undefined || value === "") return null;
  const n = Number(value);
  if (!Number.isInteger(n) || n < 1 || n > 5) throw new Error(`Row ${row}: rating "${value}" is not a whole number 1–5`);
  return n * 2;
}

export async function readPlaces(file: string): Promise<ImportedPlace[]> {
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.readFile(file);
  const sheet = workbook.getWorksheet("Viso");
  if (!sheet) throw new Error('Sheet "Viso" not found');

  const places: ImportedPlace[] = [];
  sheet.eachRow((row, number) => {
    if (number === 1) return; // header
    const nameCell = row.getCell(1).value;
    const name = cellText(nameCell);
    if (!name) return;
    const rawCategory = cellText(row.getCell(3).value);
    places.push({
      row: number,
      name,
      rating: convertRating(row.getCell(2).value, number),
      categories: cleanCategory(rawCategory),
      rawCategory,
      notes: cellText(row.getCell(4).value),
      website: nameCell && typeof nameCell === "object" && "hyperlink" in nameCell ? nameCell.hyperlink : null,
    });
  });
  return places;
}

const sql = sqlLiteral;

export function toSql(places: ImportedPlace[]): string {
  const lines = ["-- Generated by scripts/import-excel.ts. Idempotent: existing place names are skipped."];
  const categories = [...new Set(places.flatMap((p) => p.categories))].sort();
  for (const c of categories) lines.push(`INSERT INTO categories (name) VALUES (${sql(c)}) ON CONFLICT (name) DO NOTHING;`);

  for (const p of places) {
    const searchText = composeSearchText(p.name, p.categories.join(" "), CITY, p.notes);
    lines.push(
      `INSERT INTO places (name, city, website, rating, rating_imported, notes, search_text) ` +
        `SELECT ${sql(p.name)}, ${sql(CITY)}, ${sql(p.website)}, ${sql(p.rating)}, ${p.rating === null ? 0 : 1}, ` +
        `${sql(p.notes)}, ${sql(searchText)} WHERE NOT EXISTS (SELECT 1 FROM places WHERE name = ${sql(p.name)});`,
    );
    for (const c of p.categories) {
      lines.push(
        `INSERT OR IGNORE INTO place_categories (place_id, category_id) ` +
          `SELECT p.id, c.id FROM places p, categories c WHERE p.name = ${sql(p.name)} AND c.name = ${sql(c)};`,
      );
    }
  }
  return lines.join("\n") + "\n";
}

export function report(places: ImportedPlace[]): string {
  const out: string[] = [];
  const rated = places.filter((p) => p.rating !== null);
  const byRating = new Map<number, number>();
  for (const p of rated) byRating.set(p.rating!, (byRating.get(p.rating!) ?? 0) + 1);

  out.push(`Places: ${places.length} (rated ${rated.length}, unrated ${places.length - rated.length})`);
  out.push(
    `Ratings (10-point, flagged as imported): ${[...byRating].sort((a, b) => b[0] - a[0]).map(([r, n]) => `${r}→${n}`).join(", ")}`,
  );

  const mapping = new Map<string, { to: string; count: number }>();
  for (const p of places) {
    const key = p.rawCategory ?? "(empty)";
    const entry = mapping.get(key) ?? { to: p.categories.join(" + ") || "(none)", count: 0 };
    entry.count++;
    mapping.set(key, entry);
  }
  const final = new Map<string, number>();
  for (const p of places) for (const c of p.categories) final.set(c, (final.get(c) ?? 0) + 1);

  out.push(`\nCategories: ${mapping.size} raw values → ${final.size} categories`);
  out.push("Changed values:");
  for (const [raw, { to, count }] of [...mapping].sort((a, b) => a[0].localeCompare(b[0]))) {
    if (raw !== to) out.push(`  ${raw.padEnd(26)} → ${to}  (${count})`);
  }
  out.push("Resulting categories:");
  out.push(
    "  " +
      [...final]
        .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
        .map(([c, n]) => `${c} (${n})`)
        .join(", "),
  );

  const extras = places.filter((p) => p.notes || p.website || p.categories.length === 0);
  if (extras.length) {
    out.push("\nRows with notes, links or no category:");
    for (const p of extras) {
      const bits = [p.notes && `notes: ${p.notes}`, p.website && `website: ${p.website}`, p.categories.length === 0 && "no category"];
      out.push(`  row ${p.row} ${p.name}: ${bits.filter(Boolean).join("; ")}`);
    }
  }

  const seen = new Map<string, number>();
  for (const p of places) seen.set(p.name.toLowerCase(), (seen.get(p.name.toLowerCase()) ?? 0) + 1);
  const dups = [...seen].filter(([, n]) => n > 1).map(([name]) => name);
  if (dups.length) out.push(`\nWARNING: duplicate names (only the first is imported): ${dups.join(", ")}`);
  return out.join("\n");
}

if (import.meta.main) {
  const file = process.argv[2] ?? "data/Vilnius restaurants.xlsx";
  const places = await readPlaces(file);
  console.log(report(places));
  writeFileSync("data/import.sql", toSql(places));
  console.log(`\nWrote data/import.sql. Apply with:\n  npx wrangler d1 execute food-review --remote --file data/import.sql`);
}
